### ISSUE TITLE
"Error","stack":"Error: 553 Could not create file

### ISSUE THREAD

**Issue by fr-kshibata** [sergi/jsftp#163]
Im getting this error 
for this code
```
var file = 'image.jpg';
  Ftp.put('./test/'+file,'./test/directory',function(err){
    if (err)
    log.error(err);
    else {
      log.info(file,' successfully uploaded');
    }
  })
```

**Comment by fr-kshibata** [comment]
@sergi I don't know whats causing this. probably a bug in jsftp 
I have 777 permission on my remote ftp server

**Comment by fr-kshibata** [comment]
full error message
```
{"message":"553 Could not create file.","name":"Error","stack":"Error: 553 Could not create file.\n    at Ftp.parse (/Users/00831103/Workspace/project-2/image-pf-node/node_modules/jsftp/lib/jsftp.js:257:11)\n    at Ftp.parseResponse (/Users/00831103/Workspace/project-2/image-pf-node/node_modules/jsftp/lib/jsftp.js:174:8)\n    at Stream.<anonymous> (/Users/00831103/Workspace/project-2/image-pf-node/node_modules/jsftp/lib/jsftp.js:146:24)\n    at emitOne (events.js:77:13)\n    at Stream.emit (events.js:169:7)\n    at ResponseParser.reemit (/Users/00831103/Workspace/project-2/image-pf-node/node_modules/duplexer/index.js:70:25)\n    at emitOne (events.js:77:13)\n    at ResponseParser.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:146:16)\n    at ResponseParser.Readable.push (_stream_readable.js:110:10)","code":553},"msg":"553 Could not create file.","time":"2015-12-31T01:53:06.345Z","v":0}

```
