### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by kuncevic** [sergi/jsftp#179]
Just being reported that issue https://github.com/evanplaice/node-ftpsync/issues/32 with ftpsync which actually depend on 'jsftp'. The error I am getting:

```
C:\Users\Me\AppData\Roaming\nvm\v5.8.0\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:374
      socket.on("data", function(data) {
            ^

TypeError: Cannot read property 'on' of undefined
    at C:\Users\Me\AppData\Roaming\nvm\v5.8.0\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:374:13
    at C:\Users\Me\AppData\Roaming\nvm\v5.8.0\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:54:24
    at Array.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v5.8.0\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:556:14)
    at Ftp.parse (C:\Users\Me\AppData\Roaming\nvm\v5.8.0\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:237:13)
    at Ftp.parseResponse (C:\Users\Me\AppData\Roaming\nvm\v5.8.0\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:148:8)
    at Stream.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v5.8.0\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:119:24)
    at emitOne (events.js:90:13)
    at Stream.emit (events.js:182:7)
    at Stream.reemit (C:\Users\Me\AppData\Roaming\nvm\v5.8.0\node_modules\ftpsync\node_modules\duplexer\index.js:70:25)
    at emitOne (events.js:90:13)
```

**Comment by tufu9441** [comment]
Having the exact same problem...

**Comment by dakolech** [comment]
Any update?

**Comment by chouti** [comment]
Me having the exact same problem, are there any update?

**Comment by sittingbool** [comment]
me 2. In between was a message that it tried to connect to a weird port and also this:

{ Error: 421 Could not create socket.
    at Ftp.parse (/usr/local/lib/node_modules/ftpsync/node_modules/jsftp/lib/jsftp.js:233:11)
    at Ftp.parseResponse (/usr/local/lib/node_modules/ftpsync/node_modules/jsftp/lib/jsftp.js:148:8)
    at Stream.<anonymous> (/usr/local/lib/node_modules/ftpsync/node_modules/jsftp/lib/jsftp.js:119:24)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at Stream.reemit (/usr/local/lib/node_modules/ftpsync/node_modules/duplexer/index.js:70:25)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at Stream.write (/usr/local/lib/node_modules/ftpsync/node_modules/event-stream/index.js:192:12)
    at Stream.stream.write (/usr/local/lib/node_modules/ftpsync/node_modules/through/index.js:26:11) code: 421 }

**Comment by NoahDragon** [comment]
Same issue here.
https://github.com/hexojs/hexo-deployer-rsync/issues/20
https://github.com/hexojs/hexo-deployer-ftpsync/issues/16
https://github.com/hexojs/hexo-deployer-ftpsync/issues/24
