### ISSUE TITLE
Error: 550 Temporary hidden file already exists

### ISSUE THREAD

**Issue by dougmacklin** [sergi/jsftp#263]
Recently my app started to hang quite a bit during it's `ftp.put()` call. I'm trying to upload a file called homepage.json, and sometimes it fails and throws the following error:

`{ Error: 550 json/homepage.json: Temporary hidden file /json/.in.homepage.json. already exists`

followed by a stack trace (pasted below). Why is this temporary file still in existence after the last call completed? Is there a way that I could just overwrite it if it exists? I know that may not be the most elegant solution, just trying to figure out a way to get around this issue.

Thanks in advance,
Doug

Full stack trace:
```
{ Error: 550 json/homepage.json: Temporary hidden file /json/.in.homepage.json. already exists
    at module.exports.Ftp.parse (/Users/dmacklin/Sites/warriors-lambda/node_modules/jsftp/lib/jsftp.js:255:11)
    at module.exports.Ftp.parseResponse (/Users/dmacklin/Sites/warriors-lambda/node_modules/jsftp/lib/jsftp.js:171:8)
    at Stream.<anonymous> (/Users/dmacklin/Sites/warriors-lambda/node_modules/jsftp/lib/jsftp.js:139:10)
    at emitOne (events.js:115:13)
    at Stream.emit (events.js:210:7)
    at ResponseParser.reemit (/Users/dmacklin/Sites/warriors-lambda/node_modules/duplexer/index.js:70:25)
    at emitOne (events.js:115:13)
    at ResponseParser.emit (events.js:210:7)
    at readableAddChunk (/Users/dmacklin/Sites/warriors-lambda/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at ResponseParser.Readable.push (/Users/dmacklin/Sites/warriors-lambda/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at ResponseParser.Transform.push (/Users/dmacklin/Sites/warriors-lambda/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at ResponseParser.<anonymous> (/Users/dmacklin/Sites/warriors-lambda/node_modules/ftp-response-parser/index.js:62:12)
    at Array.forEach (<anonymous>)
    at ResponseParser._transform (/Users/dmacklin/Sites/warriors-lambda/node_modules/ftp-response-parser/index.js:45:9)
    at ResponseParser.Transform._read (/Users/dmacklin/Sites/warriors-lambda/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at ResponseParser.Transform._write (/Users/dmacklin/Sites/warriors-lambda/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/dmacklin/Sites/warriors-lambda/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/Users/dmacklin/Sites/warriors-lambda/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at ResponseParser.Writable.write (/Users/dmacklin/Sites/warriors-lambda/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20) code: 550 }
```

**Comment by dougmacklin** [comment]
After more research I've concluded that this issue is not one that this library should be responsible for solving.
