### ISSUE TITLE
try to open conn Unexpected token ...

### ISSUE THREAD

**Issue by ludwigmeier** [sergi/jsftp#273]
hi,
i try to open a new jsftp connection and i get this error:
testJSFTP/node_modules/jsftp/lib/jsftp.js:42
function runCmd(name, ...params) {
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

**Comment by sergi** [comment]
What version of node are you running?

**Comment by ludwigmeier** [comment]
node -v
v4.2.6

**Comment by sergi** [comment]
jsftp only works in Node 6 and up, unfortunately.
