### ISSUE TITLE
Bad passive host/port combination

### ISSUE THREAD

**Issue by jazz-soft** [sergi/jsftp#278]
Windows 10, Node v9.3.0, jsftp v2.1.3
After successful ftp.auth(..), trying ftp.get(...) and get the "Bad passive host/port combination" error.
Did I miss anything?

`Error: Bad passive host/port combination
    at Object.execute [as callback] (C:\GIFTP\giftp\giftp\node_modules\jsftp\lib\jsftp.js:644:23)
    at Ftp.parse (C:\GIFTP\giftp\giftp\node_modules\jsftp\lib\jsftp.js:228:11)
    at Ftp.parseResponse (C:\GIFTP\giftp\giftp\node_modules\jsftp\lib\jsftp.js:146:8)
    at Stream.pipeline.on.data (C:\GIFTP\giftp\giftp\node_modules\jsftp\lib\jsftp.js:112:10)
    at Stream.emit (events.js:159:13)
    at ResponseParser.reemit (C:\GIFTP\giftp\giftp\node_modules\duplexer\index.js:70:25)
    at ResponseParser.emit (events.js:159:13)
    at readableAddChunk (C:\GIFTP\giftp\giftp\node_modules\readable-stream\lib\_stream_readable.js:195:16)
    at ResponseParser.Readable.push (C:\GIFTP\giftp\giftp\node_modules\readable-stream\lib\_stream_readable.js:162:10)
    at ResponseParser.Transform.push (C:\GIFTP\giftp\giftp\node_modules\readable-stream\lib\_stream_transform.js:145:32)
`
Thank you!

**Comment by QueemJiao** [comment]
+1
